### ISSUE TITLE
testing start-nat-full.sh with android phone/chrome browser

### ISSUE THREAD

**Issue by raz3k** [sensepost/mana#12]
Hello,

 I am currently running Kali 3.14-5-1 amd64 and i installed mana-toolkit by downloading from git. I ran  ./kali-install.sh, no error encountered. After modifying the .conf and .sh to change from wlan0 -> wlan2 i ran start-nat-full.sh which created the Internet AP. 

 I have tested manually connecting my phone to the Internet AP. 
After connecting i tried: 
- starting facebook app => error loading news feed
- starting yahoo.com via chrome browser => got cert Authority invalid, clicked on proceed anyway(unsafe), refreshes, and gave me HSTS notice.

I am having issues grabbing anything.

I have also tried start-noupstream.sh which should force the client to the capture page, this didn't happened either, in this mode the client makes dns queries to 8.8.8.8 but nobody catches them neither responds to them to redirect.

Here is the output of start-nat-full.sh
http://pastebin.com/FM2QS8DM
http://pastebin.com/5xLNq8G9

Am i doing something wrong?

**Comment by singe** [comment]
The facebook app, like many apps, force the need for a valid certificate (last I checked they weren't pinning yet). If you use the captive portal you can see an example of how we try to get users to load the malicious cert.

Can you elaborate on the yahoo.com HSTS notice?

Well spotted on the DNS problem, you're exactly right, the DHCP server is pushing 8.8.8.8 out as the DNS. Rather than editing that, I added the following line to start-noupstream.sh to capture all DNS traffic and redirect it to us (in case some clients are using static DNS for the network we spoofed).
iptables -t nat -A PREROUTING -i $phy -p udp --dport 53 -j DNAT --to 10.0.0.1

Can you try again with that change?
