### ISSUE TITLE
How to use mana toolkit with airbase

### ISSUE THREAD

**Issue by rougewifi** [sensepost/mana#52]
Hii..

I'm new in wifi penetration. I'm seeking some help in using airbase-ng with mana toolkit so that I'm able to connect all open wifi automatically. 

It is working fine with karma toolkit but I'm not able to run with mana toolkit. 

I hope somebody highly experienced people / creator of mana toolkit will help me in this problem.

Regards

**Comment by singe** [comment]
Hi. mana-toolkit uses hostapd-mana *instead* of airbase-ng. In fact, one of the reasons we used hostapd is because of performance problems with airbase (it's software only and is slow, hostapd will use firmware on the card). 

If you'd like to use airbase here's a blog entry how to I wrote a few years ago https://www.sensepost.com/blog/2013/rogue-access-points-a-how-to/

**Comment by rougewifi** [comment]
Hello Mr White,

Thanks for help. 
I had read this article and it helps me in connecting open wifi devices automatically. But in mana toolkit, I'm not able to connect all wifi devices around me. It only connects with essid which we mentioned in start-nat-full.sh. 
Can you help me in what command exactly works to connect all open wifi devices around me. Or in file where should i made change to complete this task. 

Hope to hear from you soon.

Regards

**Comment by singe** [comment]
There's a description of relevant options available at https://github.com/sensepost/hostapd-mana/blob/e918abdafb6825dacf8c5b99961649456bc049f5/hostapd/hostapd.conf
