### ISSUE TITLE
Ubuntu: nl80211: Could not configure driver mode nl80211 driver initialization failed.

### ISSUE THREAD

**Issue by haisheng-zhang** [sensepost/mana#85]
Hi guys,

I'm running mana on Ubuntu.
Two questions
1. I don't see any karma conf. Is it as expected?
2. When I launch start-nat-full.sh, I get nl80211: Could not configure driver mode
nl80211 driver initialization failed. What to do with that?

Thanks in advance for any help.

**Comment by singe** [comment]
That typically means something is using the adapter, run ```airmon-ng check``` out what. I'm not sure what karma.conf is, that was never a file name I used.

This repository has been deprecated. Check out (w1f1.net)[https://w1f1.net] for the latest tooling.

I'm going to close the issue here, but feel free to reopen it on hostapd-mana's repo if you get more info.
