### ISSUE TITLE
mana-toolkit successfully creates fake AP but devices not connecting to it

### ISSUE THREAD

**Issue by vikrant17** [sensepost/mana#97]
hi, I am new to the linux and hacking world. I was trying to create fake AP using mana-toolkit "start-nat-simple.sh" command. It successfully creates a fake AP. In my devices i can see the AP name but i cannot connect to it. it tries connecting to it for sometime and den fails. Plz help me..

**Comment by singe** [comment]
It’s really hard to help with no debugging info. Try read the error messages and google them. If that doesn’t get you nearer to a fix, try disabling mana and see if you can get a vanilla network working. All of that will require some reading/experimenting on your part and you’ll probably learn a lot of worthwhile things in the end. This is what hacking is ;)

**Comment by vikrant17** [comment]
I dont get any error message. The command executes successfully an i can see the AP on my devices but it doesnt connect. (my wireless card supports AP)

**Comment by DaigneaultPearce** [comment]
Having identical issue here.
bash start-nat-simple.sh
Configuration file: /etc/mana-toolkit/hostapd-mana.conf
Using interface wlan0 with hwaddr 00:11:22:33:44:00 and ssid "Dinnernet"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
Hit enter to kill me

Cant connect any device but SSID shows up.
How can I find more useful debugging info?
How do i start troubleshooting this?
Using wifi card RT3570
Thank you

**Comment by singe** [comment]
Can you try the latest version of (hostapd-mana)[https://github.com/sensepost/hostapd-mana] and see if that works better for you. Running it with the -d will provide extensive debugging information.

This repository has been deprecated. Check out (w1f1.net)[https://w1f1.net] for the latest tooling.

I'm going to close the issue here, but feel free to reopen it on hostapd-mana's repo with debugging info.
